language: android

android:
  components:
  - build-tools-26.0.1
  - android-26
  - extra-android-m2repository
  - extra-android-support
  licenses:
    - '.+'

script:
  - "./gradlew assembleRelease"

before_install:
    - chmod +x gradlew



